### ISSUE TITLE
Question:What does green and blue histogram means?

### ISSUE THREAD

**Issue by FFFang** [MobileNativeFoundation/XCLogParser#143]
![image](https://user-images.githubusercontent.com/8197207/125076240-4177a680-e0f2-11eb-9028-d50ac6bccb52.png)

**Comment by FFFang** [comment]
Is my guess correct?
The blue one represent duration and the green one represent compilation time?

**Comment by ecamacho** [comment]
That's right. The blue one is how long did it took Xcode to actually build the product. In some cases is misleading, because Xcode compiles the code and sometimes waits until some dependencies are built before assembling the final binary. That's why we added the green one with only the compilation times

**Comment by FFFang** [comment]
thanks @ecamacho
